# Generated by Django 4.0.4 on 2022-04-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('cost', models.IntegerField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('conversion', models.IntegerField(default=0)),
                ('cv', models.IntegerField(default=0)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'amounts',
            },
        ),
        migrations.AddIndex(
            model_name='amount',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
    ]
